config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show]
  resources :ideas do
  	resources :comments, only: [:create, :update, :destroy]
    member do
      put "vote", to: "ideas#vote"
    end
  end
  resources :notifications, only: [:index]
  resources :additional_registrations, only: [:edit, :update]
  resources :category_registrations, only: [:edit, :update]
  resources :categories, only: [:index, :show]

  root 'ideas#index'
  get 'static_pages/landing'

#  devise_scope :user do
#	  authenticated :user do
#	    root to: 'ideas#index', as: :authenticated_root
#	  end
#
#	  unauthenticated do
#      root to: 'static_pages#landing', as: :unauthenticated_root
#	  end
#	end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_and_belongs_to_many :categories

  paginates_per 30
  
  acts_as_votable

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 2000 }
  validates :category_ids, presence: true
  # validates :difficulty, presence: true

  # DIFFICULTIES = ["Beginner", "Intermediate", "Professional"]
  
  # validates_inclusion_of :difficulty, :in => DIFFICULTIES

  searchable do
    text :title, :content
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :omniauthable, :omniauth_providers => [:facebook]

  has_attached_file :avatar, 
                        :styles => { :medium => "250x250#", :icon => "20X20#" }, 
                        :default_url => "default_:style_avatar.jpg",
                        :storage => :s3,
                        :s3_credentials => {
                          :bucket => ENV['S3_BUCKET_NAME'],
                          :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                          :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                        }
  validates_attachment :avatar, 
                        :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
                        :size => { :in => 0..1.megabytes }

  has_many :ideas, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_and_belongs_to_many :categories

  acts_as_voter

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 } 
  validates :email, presence: true, length: { maximum: 255 },
  									format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates_confirmation_of :password
  validates :description, length: { maximum: 100 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def new
		@idea = Idea.new
	end

	def create
		@idea = current_user.ideas.build(idea_params)
		if @idea.save
			@idea.liked_by current_user
			flash[:success] = "Idea created!"
			redirect_to @idea
		else
			flash.now[:error] = "There was an error with your idea. Please try again."
			render 'new'
		end
	end

	def edit
		@idea = Idea.find(params[:id])
	end

	def update
		@idea = Idea.find(params[:id])
		if @idea.update_attributes(idea_params)
      flash[:success] = "Idea updated!"
      redirect_to @idea
    else
    	flash.now[:error] = "There was an error with your update. Please try again."
      render 'edit'
    end
  end

  def destroy
  	@idea = current_user.ideas.find_by(id: params[:id])
  	redirect_to root_path if @idea.nil?
  	@idea.destroy
  	flash[:success] = "Idea deleted!"
  	redirect_to ideas_path
  end

	def show
		if params.has_key?(:notification_id)
			@notification = Notification.find(params[:notification_id])
	  	@notification.update_attribute(:read, true)
	  end
		@idea = Idea.find(params[:id])
		@comments = @idea.comments.all
		@comment = @idea.comments.build
	end

	def index
		if params[:search].blank?
			@ideas = Idea.all.page params[:page]
		else
			@search = Idea.solr_search do
				fulltext params[:search]
			end
			@ideas = @search.results
		end
	end

	def vote
		@idea = Idea.find(params[:id])
		if current_user.voted_for? @idea
			@idea.unliked_by current_user
		else
			@idea.liked_by current_user
		end
	end

	private

		def idea_params
			params.require(:idea).permit(:title, :content, :difficulty, :category_ids => [])
		end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_idea.html.erb
<div class="idea-entry" id="idea-<%= idea.id %>">

  <% if user_signed_in? %>
    <%= link_to vote_idea_path(idea), method: :put, remote: true do %>
      <% if current_user.voted_for? idea %>
        <div class="voted">
          <i class="fa fa-arrow-up"></i>
          <div class="vote-count"><%= idea.get_likes.size %></div>
        </div>
      <% else %>
        <div class="novote">
          <i class="fa fa-arrow-up"></i>
          <div class="vote-count"><%= idea.get_likes.size %></div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="vote">
      <div class="vote-count"><%= idea.get_likes.size %></div>
    </div>
  <% end %>

  <div class="idea-info">
    <div class="small-heading"><%= link_to idea.title, idea_path(idea) %></div>
    <!--<span class="difficulty"><%= idea.difficulty %></span><span class="circle"></span>-->  
    <% for category in idea.categories %>
      <span class="category-name"><%= link_to category.name, category_path(category) %></span>
    <% end %>
    <br />
    <%= link_to image_tag(idea.user.avatar.url(:icon)), idea.user %>
    <span class="user"><%= link_to idea.user.name, idea.user %></span>
    <div class="content">
      <%= truncate(idea.content, length: 180) %>
      <% if idea.content.length > 180 %>
        <%= link_to "See more", idea_path(idea) %>
      <% end %>
    </div>
  </div>
  <hr>
</div>

app/views/ideas/edit.html.erb
<% provide(:title, "Edit Idea") %>

<div class="heading">Edit your idea</div>

<%= form_for(@idea) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, placeholder: @idea.title, maxlength: 100 %>
  </div>

<!--
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary, placeholder: @idea.summary, maxlength: 120 %>
  </div>

  <div class="field">
    <%= f.label :problem %><br />
    <%= f.text_field :problem, placeholder: @idea.problem, maxlength: 120 %>
  </div>
-->

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, rows: "15", placeholder: @idea.content, maxlength: 2000 %>
  </div>

<!--
  <div class="field">
    <%= f.label :difficulty %>
    <ul class="multi-column">
      <li>
        <label>
          <%= f.radio_button :difficulty, "Beginner" %>
          <%= f.label :beginner %>
        </label>
      </li>
      <li>
        <label>
          <%= f.radio_button :difficulty, "Intermediate" %>
          <%= f.label :intermediate %>
        </label>
      </li>
      <li>
        <label>
          <%= f.radio_button :difficulty, "Professional" %>
          <%= f.label :professional %>
        </label>
      </li>
    </ul>
  </div>
-->

  <div class="field">
    <%= f.label :pick_at_most_3_categories %>
    <ul class="multi-column">
      <% for category in Category.all %>
        <li>
          <label>
            <%= check_box_tag "idea[category_ids][]", category.id %>
            <%= category.name %>
          </label>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit "Update Idea", class: "button" %>
  </div>
<% end %>

app/views/ideas/index.html.erb
<%= render @ideas %>
<%= paginate @ideas %>

app/views/ideas/new.html.erb
<% provide(:title, "New Idea") %>

<div class="skinny-wrapper">

  <div class="heading">Post your idea</div>

  <%= form_for(@idea) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>

  	<div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true, maxlength: 100, placeholder: "The name of your idea" %>
    </div>

  <!--
    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_field :summary, maxlength: 120, placeholder: "A one sentence summary of what your idea is" %>
    </div>

    <div class="field">
      <%= f.label :problem %><br />
      <%= f.text_field :problem, maxlength: 120 %>
    </div>
  -->

    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content, rows: "15", maxlength: 2000, placeholder: "The problem, your target audience, your implementation, etc." %>
    </div>

  <!--
    <div class="field">
      <%= f.label :difficulty %>
      <ul class="multi-column">
        <li>
          <label>
            <%= f.radio_button :difficulty, "Beginner" %>
            <%= f.label :beginner %>
          </label>
        </li>
        <li>
          <label>
            <%= f.radio_button :difficulty, "Intermediate" %>
            <%= f.label :intermediate %>
          </label>
        </li>
        <li>
          <label>
            <%= f.radio_button :difficulty, "Professional" %>
            <%= f.label :professional %>
          </label>
        </li>
      </ul>
    </div>
  -->

    <div class="field">
      <%= f.label :pick_at_most_3_categories %>
      <ul class="multi-column">
        <% for category in Category.all %>
          <li>
            <label>
              <%= check_box_tag "idea[category_ids][]", category.id %>
              <%= category.name %>
            </label>
          </li>
        <% end %>
      </ul>
    </div>
  	
  	<div class="actions">
      <%= f.submit "Post idea", class: "button" %>
    </div>
  <% end %>
</div>

<script>
  $("input[type=checkbox]").click(function() {
      var bol = $("input[type=checkbox]:checked").length >= 3;
      $("input[type=checkbox]").not(":checked").attr("disabled",bol);
  });
</script>

app/views/ideas/show.html.erb
<% provide(:title, @idea.title) %>

<div class="idea-entry" id="idea-<%= @idea.id %>">
  <div class="idea-heading"><%= @idea.title %></div>
  <!--<span class="difficulty"><%= @idea.difficulty %></span><span class="circle"></span>-->
  <% for category in @idea.categories %>
    <span class="category-name"><%= link_to category.name, category_path(category) %></span>
  <% end %>
  <br />
  <%= link_to image_tag(@idea.user.avatar.url(:icon)), @idea.user %>
  <span class="user"><%= link_to @idea.user.name, @idea.user %></span>
  <div class="content"><%= markdown(@idea.content) %></div>
  <% if current_user == @idea.user %>
    <%= link_to "Edit", edit_idea_path(@idea) %>
    <%= link_to "Delete", @idea, method: :delete,
                                       data: { confirm: "You sure?" } %>
  <% end %>
  <hr>
</div>

<% if user_signed_in? %>
  <%= form_for([@idea, @comment]) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <div class="field">
      <%= f.text_area :content, rows: "5", placeholder: "Compose new comment..." %>
    </div>

    <div class="actions">
      <%= f.submit "Post Comment", class: "btn btn-sm button" %>
    </div>
  <% end %>
<% else %>
  <div><%= link_to "You have to sign in to post comments", new_user_session_path %></div>
<% end %>

<br />

<%= render @comments %>