config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show]
  resources :ideas do
  	resources :comments, only: [:create, :update, :destroy]
    member do
      put "vote", to: "ideas#vote"
    end
  end
  resources :notifications, only: [:index]
  resources :additional_registrations, only: [:edit, :update]
  resources :category_registrations, only: [:edit, :update]
  resources :categories, only: [:index, :show]

  root 'ideas#index'
  get 'static_pages/landing'

#  devise_scope :user do
#	  authenticated :user do
#	    root to: 'ideas#index', as: :authenticated_root
#	  end
#
#	  unauthenticated do
#      root to: 'static_pages#landing', as: :unauthenticated_root
#	  end
#	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :idea
	has_many :notifications, dependent: :destroy

	validates :user_id, presence: true
	validates :idea_id, presence: true
	validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.build(comment_params)
		@comment.user = current_user
		if @comment.save
			if @idea.user != current_user
				Notification.create(
					user_id: @idea.user_id,
					idea_id: @idea.id,
					comment_id: @comment.id,
					content: current_user.name + " posted a comment on your idea.",
					read: false
				)
			end
			flash[:success] = "Comment created!"
			redirect_to @idea
		else
			flash[:error] = "There was an error with your comment. Please try again."
			redirect_to @idea
		end
	end

	def edit
		@idea = Idea.find(params[:idea_id])
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		respond_to do |format|
	    if @comment.update_attributes(comment_params)
	      format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
	      format.json { respond_with_bip(@comment) }
	    else
	      format.html { render :action => "edit" }
	      format.json { respond_with_bip(@comment) }
	    end
	  end
	end
		
	def destroy
		@comment = current_user.comments.find_by(id: params[:id])
		@idea = @comment.idea
		@comment.destroy
		flash[:success] = "Comment deleted!"
		redirect_to @idea
	end

	private

		def comment_params
			params.require(:comment).permit(:content)
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<a class="comment-entry" name="comment-<%= comment.id %>">
  <hr>
  <%= link_to image_tag(comment.user.avatar.url(:icon)), comment.user %>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <span class="timestamp">
    posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
  <br />
  <span class="content"><%= best_in_place comment, :content, :as => :textarea, :activator => "#activator-#{comment.id}", :url => idea_comment_path(comment.idea, comment) %></span>
  <br />
  <% if current_user == comment.user %>
    <a href="" id="activator-<%= comment.id %>">Edit</a>
    <%= link_to "Delete", [comment.idea, comment], method: :delete,
                                       data: { confirm: "You sure?" } %>
  <% end %>
  <br />
  <br />
</a>

app/views/comments/edit.html.erb
<% provide(:title, "Edit Comment") %>

<%= form_for([@idea, @comment]) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
  <%= f.text_area :content, placeholder: @comment.content %>
  <br />
  <%= f.submit "Update Comment", class: "btn btn-sm button" %>
<% end %>