config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show]
  resources :ideas do
  	resources :comments, only: [:create, :update, :destroy]
    member do
      put "vote", to: "ideas#vote"
    end
  end
  resources :notifications, only: [:index]
  resources :additional_registrations, only: [:edit, :update]
  resources :category_registrations, only: [:edit, :update]
  resources :categories, only: [:index, :show]

  root 'ideas#index'
  get 'static_pages/landing'

#  devise_scope :user do
#	  authenticated :user do
#	    root to: 'ideas#index', as: :authenticated_root
#	  end
#
#	  unauthenticated do
#      root to: 'static_pages#landing', as: :unauthenticated_root
#	  end
#	end
end

app/views/layouts/_footer.html.erb
<div class="footer">
	Get in touch with us at <a href="mailto:info@unicornbase.com">info@unicornbase.com</a>, we'd love hear any feedback you have!
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <li>
        <%= link_to root_path do %>
          <%= image_tag("unicorn_logo.png", size: "45") %>
          <span>Unicornbase</span>
        <% end %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="searchbar">
        <%= form_tag ideas_path, :method => :get do %>
          <% text_field_tag :search, params[:search], placeholder: "Search" %>
        <% end %>
      </li>
      <li>
        <%= link_to categories_path do %>
          <i class="fa fa-lightbulb-o fa-lg"></i>
          <span>Discover</span>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to new_idea_path do %>
            <i class="fa fa-edit fa-lg"></i>
            <span>Post</span>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-bell-o fa-lg"></i>
            <span>Notifications</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-right no-collapse" role="menu">
            <% @notifications = current_user.notifications.last(8) %>
            <%= render partial: "notifications/notification", collection: @notifications %>
            <li class="dropdown-caption"><%= link_to "See all notifications", notifications_path %></li>
          </ul>
        </li>
        <li class="dropdown profile">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= image_tag(current_user.avatar.url(:icon)) %>
            <span>Profile</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" role="menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <hr>
            <li><%= link_to "Interests", edit_category_registration_path(current_user) %></li>
          </ul>
        </li>        
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
	  </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) + " - Discover the next great startup ideas" %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <meta name="description" content="Share and discuss your business ideas with a community of aspiring entrepreneurs.">
	  <meta name="keywords" content="Startup ideas, Business ideas, Entrepreneurship">
	  <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
	  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	  <%= favicon_link_tag 'unicorn_favicon.png' %>
	</head>

	<body>
		<%= render 'layouts/header' unless @disable_nav %>

		<div class="center-content">

			<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>